---
- name: Is firewalld installed?
  shell: rpm -q firewalld > /dev/null || echo 'Not found'
  register: tmp
  changed_when: false
- set_fact:
    firewalld_installed: "{{ tmp.stdout_lines|length() == 0 }}"

- name: Update all packages
  dnf: name='*' state=latest

- systemd: name=firewalld enabled=no state=stopped masked=yes
  when: firewalld_installed

- name: Install required packages
  dnf: state=latest name={{ item }}
  with_items: "{{ required_packages }}"

- name: Install optional packages
  dnf: state=latest name={{ item }}
  with_items: "{{ optional_packages }}"

- name: Update all packages
  dnf: state=latest name='*'

- name: Set up fail2ban sshd jail on Redhat
  copy:
    src: files/sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf

- name: Directory for selinux files
  file:
    path: ~{{ deploy_user_name }}/selinux
    state: directory
    recurse: yes
  become_user: "{{ deploy_user_name }}"

- name: Set up SELinux for fail2ban working with ufw
  copy:
    src: files/my_fail2ban.te
    dest: ~{{ deploy_user_name }}/selinux/my_fail2ban.te
  notify: Install SELinux rules

- service: name=fail2ban enabled=yes state=started
