---
# Install tasks for each OS family
- include: "{{ ansible_os_family }}.yml"

- name: Enable docker service
  service: name=docker enabled=yes state=started

- name: docker group
  group: name=docker state=present
  notify:
  - restart docker

- name: Add deploy user to docker group
  user: name={{deploy_user_name}} groups=docker append=yes
  notify:
  - restart docker

# docker-compose shell script
- name: Install docker-compose as shell script
  get_url:
    url: https://github.com/docker/compose/releases/download/1.15.0/run.sh
    dest: /usr/local/bin/docker-compose
    mode: 0755

# docker-compose bash completions
- name: Set up bash completions for docker-compose
  get_url:
    url: https://github.com/docker/compose/blob/1.15.0/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: 0644
